// Mock data — substituir por chamadas reais à API conforme backends são implementados

import type {
  Patent, PortfolioAsset, AIOpportunity, Dispute,
  UFOPOpportunity, UFOPNews, PoolPatent, TTContract, Alert,
} from "./types";

export const mockPatents: Patent[] = [
  {
    id: 1,
    application_number: "BR102024TEST001",
    title: "Sistema de classificação automática de patentes via IA",
    abstract: "Método de classificação automática de patentes brasileiras utilizando modelo BERT fine-tuned nas categorias IPC.",
    applicant: "Argos Tech Ltda",
    inventors: ["Leonardo Paniago"],
    filing_date: "2024-03-15",
    publication_date: "2024-06-01",
    ipc_category: 5,
    ipc_code: "G06F",
    rpi_issue: "2024-001",
    status: "classified",
    created_at: "2026-05-23T10:00:00Z",
    updated_at: "2026-05-23T10:00:00Z",
  },
  {
    id: 2,
    application_number: "BR102023UFOP01",
    title: "Processo de biorremediação de solos contaminados",
    abstract: "Método biológico para tratamento de solos com metais pesados oriundos de atividades de mineração.",
    applicant: "UFOP",
    inventors: ["Prof. Dr. Silva", "Dra. Costa"],
    filing_date: "2023-07-10",
    publication_date: "2023-10-15",
    ipc_category: 2,
    ipc_code: "C12N",
    rpi_issue: "2023-028",
    status: "classified",
    created_at: "2026-05-20T08:00:00Z",
    updated_at: "2026-05-20T08:00:00Z",
  },
  {
    id: 3,
    application_number: "BR102022XXXXX",
    title: "Algoritmo de otimização de malha elétrica rural",
    abstract: "Sistema de controle inteligente para distribuição de energia elétrica em zonas rurais de baixa densidade.",
    applicant: "Empresa Energia S.A.",
    inventors: ["Eng. Rocha"],
    filing_date: "2022-11-20",
    publication_date: "2023-02-01",
    ipc_category: 7,
    ipc_code: "H02J",
    rpi_issue: "2023-005",
    status: "classified",
    created_at: "2026-05-18T12:00:00Z",
    updated_at: "2026-05-18T12:00:00Z",
  },
];

export const mockIpcDistribution = [
  { name: "Eng. Mecânica", value: 34, cat: 5 },
  { name: "Química", value: 28, cat: 2 },
  { name: "Eletricidade", value: 22, cat: 7 },
  { name: "Física", value: 10, cat: 6 },
  { name: "Outros", value: 6, cat: 0 },
];

export const mockCostTimeline = [
  { year: "2026", value: 14880 },
  { year: "2027", value: 16200 },
  { year: "2028", value: 18500 },
  { year: "2029", value: 21000 },
  { year: "2030", value: 24300 },
];

export const mockPortfolioAssets: PortfolioAsset[] = [
  {
    id: "pa-1",
    type: "PI",
    number: "BR102024TEST001",
    title: "Sistema de classificação automática de patentes via IA",
    owner: "Argos Tech Ltda",
    status: "active",
    filing_date: "2024-03-15",
    expiry_date: "2044-03-15",
    next_fee_date: "2026-07-15",
    cost_annual: 2100,
    cost_monthly: 175,
    cost_total: 42000,
    ipc_code: "G06F",
    blockchain_hash: "0x4f3a9b2c...",
  },
  {
    id: "pa-2",
    type: "PI",
    number: "BR102023XXXXX",
    title: "Sistema de filtros adaptativos para redes neurais",
    owner: "Argos Tech Ltda",
    status: "active",
    filing_date: "2023-06-10",
    expiry_date: "2043-06-10",
    next_fee_date: "2027-02-10",
    cost_annual: 1800,
    cost_monthly: 150,
    cost_total: 36000,
    ipc_code: "G06N",
  },
  {
    id: "pa-3",
    type: "MU",
    number: "BR302022XXXXX",
    title: "Dispositivo de interface homem-máquina compacto",
    owner: "Argos Tech Ltda",
    status: "pending",
    filing_date: "2022-11-05",
    expiry_date: "2032-11-05",
    next_fee_date: "2027-05-05",
    cost_annual: 950,
    cost_monthly: 79,
    cost_total: 9500,
    ipc_code: "G06F",
  },
  {
    id: "pa-4",
    type: "TM",
    number: "BR502024XXXXXX",
    title: "ARGOS",
    owner: "Argos Tech Ltda",
    status: "active",
    filing_date: "2024-01-20",
    expiry_date: "2034-01-20",
    next_fee_date: null,
    cost_annual: 320,
    cost_monthly: 27,
    cost_total: 3200,
  },
];

export const mockAIOpportunities: AIOpportunity[] = [
  {
    id: "opp-1",
    type: "opportunity",
    title: "Lacuna detectada: IA aplicada a refino de petróleo",
    description: "Petrobras tem 0 patentes em 'IA aplicada a refino'. Você tem tecnologia em G06F (IA) e C10G (refino). Janela de 3 anos sem depósito nessa interseção.",
    ipc_class: "C10G/G06F",
    estimated_cost: 790,
    confidence: 87,
    action_label: "Iniciar consulta de anterioridade",
  },
  {
    id: "opp-2",
    type: "risk",
    title: "Risco: patente similar depositada por concorrente",
    description: "Concorrente X depositou patente com 61% de similaridade à sua BR102024TEST001 em Jan/2026. Sua prioridade está garantida, mas monitore oposições.",
    confidence: 73,
    action_label: "Ver conflito",
  },
  {
    id: "opp-3",
    type: "opportunity",
    title: "Área em crescimento: Computação Quântica (G06N)",
    description: "Crescimento de 340% em depósitos na classe G06N nos últimos 2 anos. Seu portfolio cobre o adjacente G06F. Oportunidade de extensão.",
    ipc_class: "G06N",
    estimated_cost: 1200,
    confidence: 65,
    action_label: "Ver análise completa",
  },
];

export const mockDisputes: Dispute[] = [
  {
    id: "d-1",
    number: "ARB-2026-001",
    title: "Marca 'TechPay' vs 'TechPai' — oposição por similaridade",
    plaintiff: "TechPay Fintech S.A.",
    defendant: "TechPai Pagamentos Ltda",
    status: "in_analysis",
    opened_at: "2026-04-15",
    deadline_days: 45,
    blockchain_hash: "0x7fa3c1...",
  },
  {
    id: "d-2",
    number: "ARB-2026-002",
    title: "Violação de patente BR102024XXXXX — processo industrial",
    plaintiff: "Argos Tech Ltda",
    defendant: "Empresa Y Ind. Ltda",
    status: "urgent",
    opened_at: "2026-05-01",
    deadline_days: 12,
  },
  {
    id: "d-3",
    number: "ARB-2025-008",
    title: "Disputa de autoria — modelo de utilidade BR302022",
    plaintiff: "Inventor A",
    defendant: "Empresa Z",
    status: "mediation",
    opened_at: "2025-11-20",
    deadline_days: 90,
    blockchain_hash: "0x2bc9a7...",
  },
];

// mockUFOPOpportunities kept for reference; active UI uses inline mock in ufop/page.tsx
export const mockUFOPOpportunities: UFOPOpportunity[] = [
  {
    id: 1,
    source: "oai",
    external_id: "oai:repositorio.ufop.br:1/mock-1",
    title: "Novo método de lixiviação em pilha para mineração de lítio",
    authors: ["Prof. Dr. Marco Antônio Ferreira"],
    department: "Engenharia de Minas",
    abstract: "Desenvolvimento de método hidrometalúrgico inovador para extração de lítio de pegmatitos da região de Araçuaí com eficiência 40% superior aos métodos convencionais.",
    url: "",
    published_at: "2026-05-20T00:00:00Z",
    ipc_suggestion: "C — Química e Metalurgia",
    ipc_category: 2,
    opportunity_level: "high",
    similarity_pct: 23,
    pi_score: 8.1,
    ai_analysis: "Alto potencial de patenteabilidade na categoria C.",
    status: "new",
    publication_id: null,
    created_at: "2026-05-23T00:00:00Z",
    updated_at: "2026-05-23T00:00:00Z",
  },
  {
    id: 2,
    source: "portal",
    external_id: "https://www.ufop.br/mock-2",
    title: "Biossensor eletroquímico para detecção de metais pesados em água",
    authors: ["Prof. Dr. Paulo Souza"],
    department: "Química",
    abstract: "Sensor de baixo custo baseado em grafeno funcionalizado para detecção simultânea de chumbo, cádmio e arsênio em amostras de água com sensibilidade ppb.",
    url: "https://www.ufop.br/mock-2",
    published_at: "2026-04-28T00:00:00Z",
    ipc_suggestion: "G — Física / Tecnologia da Informação",
    ipc_category: 6,
    opportunity_level: "high",
    similarity_pct: 18,
    pi_score: 7.4,
    ai_analysis: "Alto potencial de patenteabilidade na categoria G.",
    status: "new",
    publication_id: null,
    created_at: "2026-05-23T00:00:00Z",
    updated_at: "2026-05-23T00:00:00Z",
  },
];

export const mockUFOPNews: UFOPNews[] = [
  {
    id: "n-1",
    title: "UFOP deposita patente de sistema de tratamento de água com grafeno",
    date: "2026-05-22",
    url: "#",
    pi_keywords: ["patente", "grafeno", "inovação", "INPI"],
  },
  {
    id: "n-2",
    title: "Pesquisa em biocombustíveis de segunda geração avança com nova técnica enzimática",
    date: "2026-05-18",
    url: "#",
    pi_keywords: ["biocombustível", "enzima", "processo"],
  },
  {
    id: "n-3",
    title: "UFOP e Fapemig firmam acordo para transferência de tecnologia em mineração",
    date: "2026-05-10",
    url: "#",
    pi_keywords: ["transferência de tecnologia", "mineração", "acordo"],
  },
];

export const mockPoolPatents: PoolPatent[] = [
  {
    id: "pp-1",
    number: "BR102023UFOP01",
    title: "Processo de biorremediação de solos contaminados por metais pesados",
    department: "Engenharia Ambiental",
    ipc_code: "C12N / B09C",
    license_type: "non-exclusive",
    royalty_suggestion: "3–5% sobre faturamento",
    ai_match: "Alta aderência para empresas de mineração, saneamento e remediação ambiental",
    prospectus_url: "#",
  },
  {
    id: "pp-2",
    number: "BR102022UFOP04",
    title: "Algoritmo de otimização de malha elétrica para microgrids rurais",
    department: "Engenharia Elétrica",
    ipc_code: "H02J / G06Q",
    license_type: "non-exclusive",
    royalty_suggestion: "2% + milestone de R$ 50k",
    ai_match: "Compatível com startups de energy tech, cooperativas de energia, concessionárias",
  },
  {
    id: "pp-3",
    number: "BR102024UFOP07",
    title: "Biossensor para detecção multiparamétrica de poluentes aquáticos",
    department: "Química / ICEB",
    ipc_code: "G01N / C12Q",
    license_type: "exclusive",
    royalty_suggestion: "8% exclusivo ou 4% não-exclusivo",
    ai_match: "Empresas de monitoramento ambiental, laboratórios, sistema de saneamento",
    prospectus_url: "#",
  },
];

export const mockContracts: TTContract[] = [
  {
    id: "ct-1",
    number: "TT-2024-001",
    patent_title: "Processo de biorremediação de solos contaminados",
    licensor: "UFOP (Fundep)",
    licensee: "EcoTech Soluções Ambientais Ltda",
    status: "active",
    signed_at: "2024-03-10",
    expiry_at: "2029-03-10",
    royalty_rate: 4,
    blockchain_hash: "0x9df2e1...",
    milestones: [
      { label: "Prova de conceito entregue", due_date: "2024-06-01", done: true },
      { label: "Protótipo validado", due_date: "2024-12-15", done: true },
      { label: "Produto comercial lançado", due_date: "2026-12-01", done: false },
    ],
    royalties: [
      { period: "Q1 2026", expected: 12000, received: 11400, status: "received" },
      { period: "Q2 2026", expected: 13000, received: null, status: "pending" },
      { period: "Q3 2026", expected: 13000, received: null, status: "upcoming" },
    ],
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "al-1",
    type: "term",
    label: "\"inteligência artificial\" + patentes",
    last_check: "2026-05-23T08:00:00Z",
    new_count: 3,
    status: "alert",
  },
  {
    id: "al-2",
    type: "brand",
    label: "Marca: ARGOS",
    last_check: "2026-05-23T08:00:00Z",
    new_count: 0,
    status: "ok",
  },
  {
    id: "al-3",
    type: "company",
    label: "Empresa: TechPai Pagamentos",
    last_check: "2026-05-22T20:00:00Z",
    new_count: 2,
    status: "alert",
  },
];
